kbss-cvut/s-pipes

- s-pipes-core/src/main/java/cz/cvut/spipes/function/spif/ParseDate.java
- s-pipes-core/src/test/java/cz/cvut/spipes/function/date/ParseDateTest.java
- Pattern "kk" includes hours from interval [1,24] but we want to use "H" which is from interval [0,23] so there will no longer be problems with after midnight time.
- Regarding bad pattern and non-literal value there are still exceptions. If this will make problems, we can change that.
> [Feature #21] Fix not bound value and after midnight time

- s-pipes-core/src/main/java/cz/cvut/spipes/modules/AbstractModule.java
This pull request contains features #14 and #37.
> Feature - validation constraints

- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/TableSchema.java
@Matthew-Kulich  Please revise + add documentation of column as well.
> [Upd] Add documentation of table schema

- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/TableSchema.java
Related to https://github.com/kbss-cvut/s-pipes/issues/103
> Make TableSchema errors more understandable + add diff

- s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jModule.java
The first iteration of the authentication.
> [Feature #29] Allow authentication for Rdf4jModule

- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
Implemented comments from https://github.com/kbss-cvut/s-pipes/pull/121
> Add system line separator, format function

- s-pipes-core/src/main/java/cz/cvut/spipes/registry/StreamResourceRegistry.java
- s-pipes-web/src/main/java/cz/cvut/spipes/rest/SPipesServiceController.java
- s-pipes-web/src/main/java/cz/cvut/spipes/rest/StreamResourceDTO.java
- s-pipes-web/src/main/java/cz/cvut/spipes/rest/util/MultipartFileResourceResolver.java
- s-pipes-web/src/main/java/cz/cvut/spipes/rest/util/ResourceRegisterHelper.java
- s-pipes-web/src/test/java/cz/cvut/spipes/rest/util/MultipartFileResourceResolverTest.java
> [Upd] Workaround to fix memory leakage of stream resources

- s-pipes-modules-utils/s-pipes-module-archetype/bin/generate-test-module.sh
- s-pipes-modules-utils/s-pipes-module-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- s-pipes-modules-utils/s-pipes-module-archetype/src/main/resources/archetype-resources/pom.xml
https://github.com/kbss-cvut/s-pipes/issues/145
> [Upd] Improve the module generation script

- s-pipes-modules-utils/s-pipes-module-archetype/bin/generate-test-module.sh
Partially fixes https://github.com/kbss-cvut/s-pipes/issues/145
> [Fix] Fix paths in module generation script

- doc/examples/hello-world/hello-world.sms.ttl
> [UPD] Add argument declarations to :execute-greeting function in doc/examples/hello-world/hello-world.sms.ttl

- s-pipes-modules/module-dataset-discovery/src/main/java/cz/cvut/spipes/modules/GetDatasetDescriptorsModule.java
- s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/FetchPossibleValuesModule.java
- s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/MergeFormMetadataModule.java
- s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jUpdateModule.java
- s-pipes-modules/module-sparql-endpoint/src/main/java/cz/cvut/spipes/modules/ApplyConstructAbstractModule.java
- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
- s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/ExtractTermOccurrencesModule.java
I updated documentation that I could do without a sophisticated analysis of modules. 
I suggest closing the issue if they are understandable and leaving the rest of the TODO comments in code (we will do a bigger revision when we are able to generate documentation of modules).
> [#218] Improve documentation of parameters

- s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
Shows appropriate logs for issue #223.
> [Upd] Improve logs when reading input file with tabular data fails

- s-pipes-core/src/main/java/cz/cvut/spipes/util/QueryUtils.java
> [Fixes #233] Fix extracting query comment from query string.

- s-pipes-core/src/main/java/cz/cvut/spipes/modules/AbstractModule.java
> Validation error shows evidences columns in wrong order

- s-pipes-web/src/main/java/cz/cvut/spipes/rest/handler/ErrorValidationResponse.java
> Add message field to the ErrorValidationResponse.

- s-pipes-core/src/main/java/cz/cvut/spipes/modules/AbstractModule.java
Reverted these changes:
```java
evidenceMap.put(varName, RDFNodeUtils.toString(value));
```
> Revert RDFNode conversion changes

- s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java
> Symbolic links

- s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/RepositoryManagerHandler.java
- s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jCreateRepositoryModule.java
Resolves https://github.com/kbss-cvut/s-pipes/issues/300
> [#300] Fixed rdf4jCreateRepositoryModule

- doc/examples/rdf4j-update/rdf4j-update.sms.ttl
- s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jUpdateModule.java
Resolves https://github.com/kbss-cvut/s-pipes/issues/175
> [#175] Use prefixes supported by rdf4j update module

- s-pipes-web/src/main/java/cz/cvut/spipes/rest/util/ProgressListenerLoader.java
Resolves https://github.com/kbss-cvut/s-pipes/issues/337
> [#333] Added logging of the fact which progress listener is being used

- deploy/docker-compose.yml
- deploy/s-pipes-engine/s-pipes-progress-listener-config.ttl
- s-pipes-debug/src/main/resources/application.properties
Relates to https://github.com/kbss-cvut/s-pipes/issues/336
> [#336] Add setting of configurl from docker-compose.yml

- s-pipes-debug/src/main/resources/logback.xml
>  logback.xml configuration

- s-pipes-debug/pom.xml
- s-pipes-debug/src/main/java/cz/cvut/spipes/debug/persistance/PersistenceFactory.java
- s-pipes-debug/src/main/java/cz/cvut/spipes/debug/util/SPipesDebugClassPathScanner.java
Resolves https://github.com/kbss-cvut/s-pipes/issues/336
> [#336] Added Spring Boot Loader to support nested jars

- s-pipes-debug/doc/hands-on-tutorial/hands-on-tutorial.md
Resolves https://github.com/kbss-cvut/s-pipes/issues/316
> [#316] Add tutorial for s-pipes-debug

- s-pipes-debug/pom.xml
- s-pipes-parent/pom.xml
Resolves https://github.com/kbss-cvut/s-pipes/issues/361
> [#361] Update jb4jsonld

- s-pipes-forms/src/main/java/cz/cvut/sforms/util/SPipesFormsClassPathScanner.java
- s-pipes-forms/src/main/java/cz/cvut/spipes/transform/SPipesUtil.java
Related to https://github.com/kbss-cvut/s-pipes-editor-ui/issues/151
> Add support for nested jars in s-pipes-forms

- s-pipes-cli/src/main/java/cz/cvut/spipes/cli/ExecuteModuleCLI.java
- s-pipes-core/src/main/java/cz/cvut/spipes/config/ContextsConfig.java
- s-pipes-web/src/main/java/cz/cvut/spipes/rest/util/ContextLoaderHelper.java
Partially implements #366.
@kostobog currently we do not use CLI, so you can reuse temporarily this part of code to run whatever u need (although I am not sure if it helps you). Definitely, read first #366.
> Partial implementation CLI parameter for module-type 

- s-pipes-debug/src/main/resources/application.properties
Related to https://github.com/kbss-cvut/s-pipes/issues/325
> [325] Remove bean override

- deploy/docker-compose.yml
- deploy/nginx/index.html
- deploy/nginx/nginx.conf
Resolves https://github.com/kbss-cvut/s-pipes/issues/368
> [#368] Improve S-Pipes Dashboard

- s-pipes-core/pom.xml
- s-pipes-forms/pom.xml
- s-pipes-parent/pom.xml
@blcham 
Fixes #410, fixes incomplete PR #398
> Bump shacl dependency version in s-pipes-forms 1.0.1 --> 1.4.4

- doc/examples/hello-world/hello-world.sms.ttl
Resolves https://github.com/kbss-cvut/s-pipes/issues/418
> [#418] Update hello-world.sms.ttl example to use SHACL

- s-pipes-cli/src/main/java/cz/cvut/spipes/cli/ExecuteModuleCLI.java
- s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java
- s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntologyDocumentManager.java
- s-pipes-core/src/main/java/cz/cvut/spipes/manager/SPipesScriptManager.java
- s-pipes-core/src/main/java/cz/cvut/spipes/util/SPipesUtil.java
- s-pipes-core/src/test/java/cz/cvut/shacl/SHACLIntegrationTest.java
- s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java
- s-pipes-core/src/test/resources/shacl/shacl-function.shacl.ttl
- s-pipes-web/src/main/java/cz/cvut/spipes/rest/SPipesServiceController.java
> Fix model cache and its resetting

- s-pipes-core/src/main/java/cz/cvut/spipes/function/spif/ParseDate.java
- s-pipes-core/src/test/java/cz/cvut/spipes/function/date/ParseDateTest.java
>  Add implement support for 2 argument parseDate variant
